APP_TYPES = [
    "workflow",  # workflow
    "advanced-chat",  # chatflow
    # "chat",
    # "agent-chat",
    # "completion",
]

DEFAULT_TEMPLATES = {
    "advanced-chat": {
        "graph": {
            "nodes": [
                {
                    "id": "1755439783606",
                    "type": "custom",
                    "data": {
                        "type": "start",
                        "title": "开始",
                        "desc": "",
                        "variables": [],
                        "selected": False,
                    },
                    "position": {"x": 80, "y": 282},
                    "targetPosition": "left",
                    "sourcePosition": "right",
                    "positionAbsolute": {"x": 80, "y": 282},
                    "width": 244,
                    "height": 54,
                },
                {
                    "id": "llm",
                    "type": "custom",
                    "data": {
                        "type": "llm",
                        "title": "LLM",
                        "desc": "",
                        "variables": [],
                        "model": {
                            "provider": "langgenius/siliconflow/siliconflow",
                            "name": "deepseek-ai/DeepSeek-V3",
                            "mode": "chat",
                            "completion_params": {"temperature": 0.7},
                        },
                        "prompt_template": [{"role": "system", "text": ""}],
                        "context": {"enabled": False, "variable_selector": []},
                        "vision": {"enabled": False},
                        "memory": {
                            "window": {"enabled": False, "size": 10},
                            "query_prompt_template": "{{#sys.query#}}\n\n{{#sys.files#}}",
                            "role_prefix": {"user": "", "assistant": ""},
                        },
                        "selected": False,
                    },
                    "position": {"x": 380, "y": 282},
                    "targetPosition": "left",
                    "sourcePosition": "right",
                    "positionAbsolute": {"x": 380, "y": 282},
                    "width": 244,
                    "height": 90,
                },
                {
                    "id": "answer",
                    "type": "custom",
                    "data": {
                        "type": "answer",
                        "title": "直接回复",
                        "desc": "",
                        "variables": [],
                        "answer": "{{#llm.text#}}",
                        "selected": False,
                    },
                    "position": {"x": 680, "y": 282},
                    "targetPosition": "left",
                    "sourcePosition": "right",
                    "positionAbsolute": {"x": 680, "y": 282},
                    "width": 244,
                    "height": 105,
                },
            ],
            "edges": [
                {
                    "id": "1755439783606-llm",
                    "source": "1755439783606",
                    "sourceHandle": "source",
                    "target": "llm",
                    "targetHandle": "target",
                    "type": "custom",
                    "data": {"sourceType": "start", "targetType": "llm"},
                },
                {
                    "id": "llm-answer",
                    "source": "llm",
                    "sourceHandle": "source",
                    "target": "answer",
                    "targetHandle": "target",
                    "type": "custom",
                    "data": {"sourceType": "llm", "targetType": "answer"},
                },
            ],
            "viewport": {"x": 0, "y": 0, "zoom": 1},
        },
        "features": {
            "opening_statement": "",
            "suggested_questions": [],
            "suggested_questions_after_answer": {"enabled": False},
            "text_to_speech": {"enabled": False, "voice": "", "language": ""},
            "speech_to_text": {"enabled": False},
            "retriever_resource": {"enabled": True},
            "sensitive_word_avoidance": {"enabled": False},
            "file_upload": {
                "image": {
                    "enabled": False,
                    "number_limits": 3,
                    "transfer_methods": ["local_file", "remote_url"],
                },
                "enabled": False,
                "allowed_file_types": ["image"],
                "allowed_file_extensions": [
                    ".JPG",
                    ".JPEG",
                    ".PNG",
                    ".GIF",
                    ".WEBP",
                    ".SVG",
                ],
                "allowed_file_upload_methods": ["local_file", "remote_url"],
                "number_limits": 3,
                "fileUploadConfig": {
                    "file_size_limit": 15,
                    "batch_count_limit": 5,
                    "image_file_size_limit": 10,
                    "video_file_size_limit": 100,
                    "audio_file_size_limit": 50,
                    "workflow_file_upload_limit": 10,
                },
            },
        },
        "environment_variables": [],
        "conversation_variables": [],
        "hash": "600f17463b514f0606a5cc21d31a25f66e12d4848eba23f81b1cd927663d9d27",
    }
}
